# Makefile.dep created Tue Apr 14 01:21:05 PDT 2015
commands.o: commands.cpp commands.h inode.h util.h debug.h
debug.o: debug.cpp debug.h util.h
inode.o: inode.cpp debug.h inode.h util.h
util.o: util.cpp util.h debug.h
main.o: main.cpp commands.h inode.h util.h debug.h
