#Brandon Jarvinen (bjarvine@ucsc.edu)
#Fan Zhang (fzhang12@ucsc.edu)
trace.o: trace.cpp trace.h
util.o: util.cpp util.h trace.h util.tcc
main.o: main.cpp listmap.h xless.h xpair.h listmap.tcc trace.h util.h \
 util.tcc
